# Default values for lets-chat.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
progressDeadlineSeconds: 300
spec:
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
image:
  repository: rameshpoomalai/lets-chat
  tag: v3
  pullPolicy: IfNotPresent
service:
  name: lets-chat
  tier: frontend
  type: NodePort
  protocol: TCP
  internalPort: 8080
  externalPort: 8080
  nodeport: 30080
mongo:
  host: mongo
ingress:
  enabled: false
resources:
  limits:
    memory: 512Mi
  requests:
    memory: 128Mi
